version: '3.4'

services:
  db:
    image: rest-with-asp-net-api-db
    command: sqlServerd --default-authentication-plugin=sqlserver_native_password
    restart: always
    build:
      context: .
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MSSQLSERVER01: GabrielRibeiro\MSSQLSERVER01
      User Id: desenvolvimento
      Password: ga0904
      Database: CursoUdemy
    ports:
      - 3308:3306
    networks:
      - udemy-network
      
  rest-with-asp-net-api:
    image: rest-with-asp-net-api
    build:
      context: .
      dockerfile: RestWithAspNET.API/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - 44300:80
    depends_on:
      - db
    networks:
      - udemy-network
networks:
  udemy-network:
    driver: bridge
    
